abstract class Routes {
  Routes._();
  static const HOME = "/home";
  static const ONBOARDING = "/onboarding";
  static const LOGIN = "/login";
  static const OTP = "/otp";
  static const MAINPAGE = "/mainpage";
  static const SIGNUPPAGE = "/signup";
  static const CARTPAGE = "/checkoutpage";
  static const ADDNEWADDRESSPAGE = "/newaddresspage";
  static const PAYMENTPAGE = "/paymentpage";
  static const CATEGORYBYGENDERPAGE = "/categorybygender";
  static const MYORDERPAGE = "/orderpage";
  static const PRESCRIPTIONPAGE = "/prescription";
  static const OTPPHONENUMBERPAGE = "/inputnumberotp";
  static const NOTIFICATION = "/notification";
  static const PROFILESETTING = "/profilesetting";
  static const WISHLISTPAGE = "/wishlist";
  static const WALLETPAGE = "/walletpage";
  static const COUPONSPAGE = "/coupouns";
  static const REDDEMPAGE = "/reddem";
  static const PRODUCTDESCRIPTIONPAGE = "/productdescriptionpage";
  static const CATEGORYWISEPRODUCT = "/categorywiseproduct";
  static const SELECTPRESCRIPTIONPAGE = "/selectprescriptionpage";
  static const GETADDTOCART = "/api/get_addCart";
  static const SELECTADDRESS = "/selctaddress";
  static const GENDERWISEPRODUCTPAGE = "/genderwiseproductpage";
  static const INVOICEPAGE = "/invoicepage";
  static const BLOGDETAILPAGE = "/blogdetailpage";
}
